version: '3'
services:
  app:
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '81:81'
      - '443:443'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "%MYSQL_USER"
      DB_MYSQL_PASSWORD: "%MYSQL_PASSWORD"
      DB_MYSQL_NAME: "%MYSQL_DATABASE"
    volumes:
      - /srv/config/nginxproxymanager:/data
      - /srv/config/nginxproxymanager/letsencrypt:/etc/letsencrypt
  db:
    image: 'jc21/mariadb-aria:latest'
    environment:
      MYSQL_ROOT_PASSWORD: '%MYSQL_ROOT_PASSWORD'
      MYSQL_DATABASE: '%MYSQL_DATABASE'
      MYSQL_USER: '%MYSQL_USER'
      MYSQL_PASSWORD: '%MYSQL_PASSWORD'
    volumes:
      - /srv/config/nginxproxymanager/db:/var/lib/mysql
