---
version: "2"
services:
  bookstack:
    image: linuxserver/bookstack
    container_name: bookstack
    environment:
      - PUID=1000
      - PGID=1000
      - DB_HOST=bookstack_db
      - DB_USER=%user%
      - DB_PASS=%pass%
      - DB_DATABASE=bookstackapp
    volumes:
      - /srv/config/bookstack:/config
    ports:
      - 6875:80
    restart: unless-stopped
    depends_on:
      - bookstack_db
  bookstack_db:
    image: linuxserver/mariadb
    container_name: bookstack_db
    environment:
      - PUID=1000
      - PGID=1000
      - MYSQL_ROOT_PASSWORD=%mysql_root_pass%
      - TZ=America/Chicago
      - MYSQL_DATABASE=bookstackapp
      - MYSQL_USER=%mysql_user%
      - MYSQL_PASSWORD=%mysql_pass%
    volumes:
      - /srv/config/bookstack/DB:/config
    restart: unless-stopped